version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/github.com/suryatresna/gogql-boilerplate
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      APP_REDIS: gogql.redis.local
      APP_NAME: gogql
      PATH_PROJECT: github.com/suryatresna/gogql-boilerplate
    command: ['make','run-dev']
    container_name: gogql.app.local

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: gogql.redis.local